services:
  mysql:
    build:
      context: ./02_database
      dockerfile: Dockerfile
    container_name: mysql8-kr_TEAM_1ST
    restart: unless-stopped

    env_file:
      - ./.env

    ports:
      - "13306:3306"

    volumes:
      - ./02_database/init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD --silent" ]
      interval: 10s
      timeout: 5s
      retries: 10

  streamlit:
    build:
      context: .
      dockerfile: 05_streamlit_app/Dockerfile
    container_name: streamlit_flex1st
    restart: unless-stopped

    env_file:
      - ./.env

    ports:
      - "8501:8501"

    depends_on:
      mysql:
        condition: service_healthy