version: "3.9"

services:
  mysql:
    build:
      context: ./02_database
      dockerfile: Dockerfile
    container_name: mysql8-kr_flex1st
    restart: unless-stopped

    env_file:
      - ./02_database/.env

    ports:
      - "13306:3306"

    volumes:
      - ./02_database/init:/docker-entrypoint-initdb.d:ro
      - ./02_database:/var/lib/02_database
      - ./02_database/backup:/backup

    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD --silent" ]
      interval: 10s
      timeout: 5s
      retries: 10
